FROM golang:1.24.5-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /go-app .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /go-app .

CMD ["./go-app"]